### ISSUE TITLE
Significant Discrepancy in MS3 Results with Provided Checkpoints  

### ISSUE THREAD

**Issue by jiaqihuang01** [GeWu-Lab/Stepping-Stones#6]
Thank you for sharing your resources and pretrained checkpoints. However, I encountered a reproducibility issue when evaluating the provided weights, particularly for the MS3 subset. The metrics I obtained differ significantly from those reported in the paper.  

Here’s a comparison of the reported metrics and my results:  

| Subset | Reported mIoU | Reported F-score | My mIoU | My F-score |
|--------|---------------|------------------|---------|------------|
| S4     | 83.18         | 91.33           | 82.69   | 91.29      |
| **MS3**| **67.30**     | **77.63**       | **58.70**| **75.14**  |
| AVSS   | 48.50         | 53.20           | 47.91   | 52.33      |  

The discrepancy for MS3 is particularly large, with my results being nearly 9 points lower in mIoU compared to the reported value (67.30 vs. 58.70).  
Are there any additional steps required for MS3 evaluation that are not mentioned in the documentation?  
I would greatly appreciate your clarification to resolve this discrepancy. Thank you for your attention!

**Comment by ucasmjc** [comment]
Thank you for your attention! Before uploading, I had checked the accuracy of the checkpoint, so there shouldn't be any issues. I apologize, but I have already left from the AVS research field and currently don't have convenient access to the dataset for quick verification. If you're in urgent need of results, you can retrain the v1m task following the instructions in the README. Since the v1m dataset is quite small, it shouldn't consume too many resources. 
Please let me know if you have any further progress. Also, if the opportunity arises, I will examine the checkpoint in the future in person.
